12.1.4 构建模型
构建模型包括划分训练集和测试集、 建立模型并预测、 模型优化， 具体工作如下：
1） 划分训练集和测试集。 代码如表 12-10 所示。
表 12-10 划分数据集代码
划分数据集代码
# 分层抽样
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X_train, y, test_size=0.2, random_state=0,
stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape) #(5625, 20) (1407, 20) (5625, 1)
(1407, 1)
#修正索引
for i in[X_train, X_test, y_train, y_test]:
i.index = range(i.shape[0])
# 保存标准化训练和测试数据
st= StandardScaler()
num_scaled_train= pd.DataFrame(st.fit_transform(X_train[num_cols]), columns=num_cols)
num_scaled_test= pd.DataFrame(st.transform(X_test[num_cols]), columns=num_cols)
X_train_scaled= pd.concat([X_train.drop(num_cols, axis= 1), num_scaled_train], axis= 1)
X_test_scaled= pd.concat([X_test.drop(num_cols, axis= 1), num_scaled_test], axis= 1)
2） 建立模型并预测。 主要通过训练集对逻辑回归、 K 最近邻、 SVM、 多层感知机（MLP）、朴素贝叶斯、 决策树、 随机森林等模型进行训练并评估， 最后用训练好的模型实现预测。 代
码如表 12-11 所示。
表 12-11 建立模型并进行预测代码
建立模型并进行预测代码
# 建模
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.Naïve_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
# 模型评估
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import recall_score, precision_score, f1_score
def model_report(model, X_train, X_test, y_train, y_test, name) :
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_score = model.predict_proba(X_test)[:,1]
# 评估指标
accuracy = accuracy_score(y_test, y_pred)
recallscore = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_score)
f1score = f1_score(y_test, y_pred)
# 保存数据
df = pd.DataFrame({"Model" : [name],
"Accuracy_score" : ["{:.2f}".format(accuracy)],
"Recall_score" : ["{:.2f}".format(recallscore)],
"Precision" : ["{:.2f}".format(precision)],"f1_score" : ["{:.2f}".format(f1score)],
"Area_under_curve": ["{:.2f}".format(roc_auc)],
})
return df
# 模型
logit = LogisticRegression()
knn = KNeighborsClassifier(n_neighbors=5)
svc_lin = SVC(kernel='linear', random_state=0)
svc_rbf = SVC(kernel='rbf', random_state=0)
mlp_model = MLPClassifier(hidden_layer_sizes=(8,), alpha=0.05, max_iter=50000,
activation='logistic', random_state=0)
gnb = GaussianNB()
decision_tree = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=0)
rfc = RandomForestClassifier(n_estimators=100, random_state=0)
lgbm_c = LGBMClassifier(boosting_type='gbdt', n_estimators=100, random_state=0)
xgc = XGBClassifier(n_estimators=100, eta=0.02, max_depth=15, random_state=0,
learning_rate=0.001)
# 调用函数
model1 = model_report(logit, X_train_sclaed, X_test_sclaed, y_train, y_test,
"Logistic Regression")
model2 = model_report(knn, X_train_sclaed, X_test_sclaed, y_train, y_test,
"KNN Classifier")
model3 = model_report(svc_lin, X_train_sclaed, X_test_sclaed, y_train, y_test,
"SVM Classifier Linear")
model4 = model_report(svc_rbf, X_train_sclaed, X_test_sclaed, y_train, y_test,
"SVM Classifier RBF")
model5 = model_report(mlp_model, X_train_sclaed, X_test_sclaed, y_train, y_test,
"MLP Classifier")
model6 = model_report(gnb, X_train, X_test, y_train, y_test,"Naïve Bayes")
model7 = model_report(decision_tree, X_train, X_test, y_train, y_test,
"Decision Tree")
model8 = model_report(rfc, X_train, X_test, y_train, y_test,
"Random Forest Classifier")
model9 = model_report(lgbm_c, X_train, X_test, y_train, y_test,
"LGBM Classifier")
model10 = model_report(xgc, X_train, X_test, y_train, y_test,
"XGBoost Classifier")
# 拼接表
model_performances = pd.concat([model1, model2, model3,
model4, model5, model6,
model7, model8, model9, model10],
axis=0).reset_index()
model_performances = model_performances.drop(columns="index",axis =1)
table = ff.create_table(np.round(model_performances, 4))
# 设置表格字体大小
for i in range(len(table.layout.annotations)):
table.layout.annotations[i].font.size = 20
py.offline.iplot(table)
结果如图 12-10 所示。
在模型评估中， 将对该结果进行分析评定。
3） 模型优化。 使用 GridSearchCV 方法（ 网格搜索+交叉验证） 对决策树模型进行调参
优化。 GridSearchCV 有几个主要参数：
estimator： 选择使用的分类器， 设为决策树分类器 DecisionTreeClassifier；
param_grid 为分类器需要优化的参数的取值， 值为字典或者列表， 本案例主要设置 splitter
（用来控制决策树生成时“节点” 的选择方式） 、 criterion（用来决定节点 “重要性” 的评
估方式） 、 max_depth（决策树的最大层数， 避免出现过拟合） 三个参数及取值范围；
cv： 交叉验证参数， 值设为 10， 即使用十折交叉验证。图 12-10 模型预测结果
GridSearchCV 在指定的参数范围内， 按步长依次调整参数， 利用调整的参数训练学习器，
从所有的参数中找到在验证集上精度最高的参数。 并将这些参数用于测试集的预测。 代码如
表 12-12 所示。
表 12-12 决策树参数优化代码
决策树参数优化代码
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
parameters = { 'splitter': ( 'best', 'random'),
'criterion': ( "gini", "entropy"),
"max_depth": [* range( 3, 20)],
} c
lf = DecisionTreeClassifier(random_state= 25)
GS = GridSearchCV(clf, parameters, scoring= 'f1', cv= 10)
GS.fit(X_train, y_train)
print(GS.best_params_)
print(GS.best_score_)
clf = GS.best_estimator_
test_pred = clf.predict(X_test)
print('测试集： \n', classification_report(y_test, test_pred))
输出结果如图 12-11 所示。 可以看出调优后的决策树优先选择更“重要”的特征进行分枝，
使用信息增益（information gain） 选择节点， 最大层数为 5。图 12-11 调优后的决策树参数
将决策树绘制出来， 由于 5 层决策树层数较深， 为便于展示绘制一棵三层决策树以帮助
理解。 代码如表 12-13 所示。
表 12-13 绘制决策树代码
绘制决策树代码
import graphviz
part_DT = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)
part_DT.fit(X_train, y_train)
dot_data = tree.export_graphviz(decision_tree=part_DT, max_depth=3,
out_file=None,
feature_names=X_train.columns,
class_names=['not_churn', 'churn'],
filled=True,
rounded=True
)
graph = graphviz.Source(dot_data)
graph
如图 12-12 所示：
图 12-12 决策树决策树中各属性的信息增益度可以用于衡量该属性对分类的重要程度， 根据信息增益度
将决策树属性按重要性排序并输出， 代码如表 12-14 所示。
表 12-14 决策树属性重要性排序代码
决策树属性重要性排序代码
import plotly.figure_factory as ff
import plotly as py
imp = pd.DataFrame(zip(X_train.columns, clf.feature_importances_))
imp.columns = ['feature', 'importances']
imp = imp.sort_values('importances', ascending=False)
imp = imp[imp['importances'] != 0]
imp['importances'] = imp['importances'].apply(lambda x: "{:.2f}".format(x))
table = ff.create_table(np.round(imp, 4))
for i in range(len(table.layout.annotations)):
table.layout.annotations[i].font.size = 20
py.offline.iplot(table)
结果如图 12-13 所示：
图 12-13 决策树属性重要性排序
12.1.5 评估模型
将各模型的 ROC 曲线绘制出来， 代码如表 12-15 所示。表 12-15 绘制 ROC 曲线代码
绘制 ROC 曲线代码
from matplotlib import pyplot as plt
from sklearn.metrics import roc_curve, auc
fprs = []
tprs = []
aucs=[]
def roc_img(model, X_train, X_test, y_train, y_test, name):
model.fit(X_train, y_train)
y_score = model.predict_proba(X_test)[:,1]
fpr, tpr, thresholds = roc_curve(y_test, y_score)
roc_auc = auc(fpr,tpr)
print(roc_auc)
fprs.append(fpr)
tprs.append(tpr)
aucs.append(roc_auc)
models = [logit, knn, svc_lin, svc_rbf, mlp_model, gnb, decision_tree, rfc, lgbm_c, xgc]
names = [ "Logistic Regression", "KNN Classifier", "SVM Clissifier Linear",
"SVM Classifier RBF","MLP Classifier", "Naïve Bayes", "Decision Tree",
"Random Forest Classifier", "LGBM Classifier", "XGBoost Classifier"]
for i in range(10):
if i<5:
roc_img(models[i], X_train_scaled, X_test_scaled, y_train, y_test, names[i])
else:
roc_img(models[i], X_train, X_test, y_train, y_test, names[i])
plt.plot(fprs[i],tprs[i], lw=1.5, label="%s, AUC=%.3f"%(names[i],aucs[i]))
plt.xlabel("FPR",fontsize=15)
plt.ylabel("TPR",fontsize=15)
plt.title("ROC")
plt.legend(loc="lower right")plt.show()
结果如图 12-14 所示：
图 12-14 各模型 ROC 曲线
各分类模型的性能如表 12-16 所示， 其中加粗数值为每个指标的最优模型结果。
表 12-16 模型各指标结果
Model
Accuracy_sco
re
Recall_score Precision f1_score
Area_under_c
urve
Logistic Regression 0.80 0.52 0.66 0.58 0.84
KNN Classifier 0.78 0.51 0.60 0.55 0.77
SVM Classifier
Linear
0.80 0.46 0.69 0.55 0.83
SVM Classifier RBF 0.80 0.48 0.68 0.57 0.79
MLP Classifier 0.80 0.52 0.66 0.58 0.84
Naïve Bayes 0.72 0.78 0.49 0.60 0.83
Decision Tree 0.78 0.52 0.61 0.56 0.82Random Forest
Classifier
0. 78 0.47 0.62 0.54 0.82
LGBM Classifier 0.80 0.51 0.66 0.57 0.84
XGBoost Classifier 0.77 0.52 0.57 0.55 0.82
使用的评价指标共有五种：
(1)准确率（ Accuracy_score） ： 该指标衡量的是分类任务中正确分类样本所占的比例，
以百分比形式表示。 其计算过程可通过调用 sklearn.metrics 库中的 accuracy_score 函数实现。
(2)召回率（Recall_score） ： 该指标衡量在所有实际为正类别的样本中， 模型正确预测为
正类别的比例。 通过调用 sklearn.metrics 库中的 recall_score 函数进行计算。
(3)精确率（Precision） ： 该指标反映在模型预测为正类别的样本中， 实际为正类别的样
本所占的比例。 通过调用 sklearn.metrics 库中的 precision_score 函数进行计算。
(4)F1 分数： F-Measure 是一种统计量， 亦称为 F-Score， 其定义为精确率（Precision） 与
召回率（Recall） 的加权调和平均值。 特别地， F1 值的计算公式为
2 ∗ 𝑃𝑟𝑒𝑐� ∗ �𝑟���
𝑃𝑟𝑒𝑐� + �𝑟���
(5)曲线下面积（Area Under Curve, AUC） ： AUC 指的是接收者操作特征曲线（Receiver
Operating Characteristic, ROC） 下的面积。 本案例采用 sklearn.metrics 中的 roc_auc_score 方法
计算。
可以看出准确率（Accuracy） 指标上高斯核 SVM 模型表现最好； 召回率（Recall） 和 f1
score 指标上 Naïve Bayes 模型表现最好； 精确率（Precision） 指标上线性 SVM 模型表现最好；
AUC 指标上逻辑回归模型表现最好； 而 Kappa 系数则是 MLP 模型表现最好。
对这些模型， 分别针对各指标进行比较， 比较时数值仅四舍五入精确到小数点后两位，
得到各指标下各模型的 win/tie/lose（赢/平/输） 结果， 如表 12- 17 所示。
表 12-17 win/tie/lose 表
Model Accuracy_score Recall_score Precision f1_score
Area_under_
curve
Logistic
Regression
5/3/1 5/0/4 5/2/2 6/1/2 8/1/0
KNN Classifier 2/0/7 3/1/5 2/0/7 2/1/6 0/0/9
SVM Classifier
Linear
5/3/1 0/0/9 9/0/0 2/1/6 3/3/3
SVM Classifier
RBF
9/0/0 2/0/7 8/0/1 4/1/4 1/0/8
MLP Classifier 5/3/1 6/2/1 5/2/2 8/0/1 8/1/0
Naïve Bayes 0/0/9 9/0/0 0/0/9 9/0/0 3/3/3
Decision Tree 3/1/5 6/2/1 3/0/6 4/1/4 3/3/3Random Forest
Classifier
3/1/5 1/0/8 4/0/5 0/0/9 2/0/7
LGBM
Classifier
5/3/1 3/1/5 5/2/2 6/1/2 7/0/2
XGBoost
Classifier
1/0/8 6/2/1 1/0/8 1/0/8 3/3/3